"use client";

import type { BallotOption, MethodId } from "@/lib/domain/methods/types";
import {
  addToRanking,
  moveInRanking,
  nudgeDot,
  removeFromRanking,
  setScore,
  toggleApproval,
} from "@/lib/domain/methods/ballot-updates";

/**
 * The ballot itself, one editor per method.
 *
 * Each editor's only job is to produce a valid ballot object and hand it up.
 * It never computes the signed message — that comes from the shared
 * `canonicalBallot`, so what the voter reads before signing is generated by the
 * exact code the server verifies against, not by a parallel implementation in
 * the UI that could drift from it.
 */
export interface BallotEditorProps {
  method: MethodId;
  options: BallotOption[];
  dotBudget: number;
  ballot: unknown;
  /**
   * Takes an updater, not a value, deliberately. Every control here edits part
   * of a ballot the rest of which must survive, and a value built from the
   * `ballot` prop is built from the last *rendered* state. Two taps landing in
   * one frame would then both derive from the same stale ballot and the first
   * would be lost — which is exactly how a voter silently loses a dot.
   */
  onChange: (updater: (prev: unknown) => unknown) => void;
}

const fieldLabel = "block text-sm font-medium text-fg-primary";
const chip =
  "px-4 py-2 rounded-control border transition-colors border-default text-fg-primary";
const chipOn = "bg-surface-raised";
const chipOff = "bg-surface-base hover:bg-surface-raised";

export default function BallotEditor({
  method,
  options,
  dotBudget,
  ballot,
  onChange,
}: BallotEditorProps) {
  if (method === "single_choice") {
    const current = (ballot as { choice?: string })?.choice ?? "yes";
    return (
      <div>
        <span className={fieldLabel}>Your choice</span>
        <div className="mt-1 flex flex-wrap gap-3">
          {(["yes", "no", "abstain"] as const).map((c) => (
            <button
              key={c}
              type="button"
              onClick={() => onChange(() => ({ method, choice: c }))}
              className={`${chip} ${current === c ? chipOn : chipOff}`}
            >
              {c.toUpperCase()}
            </button>
          ))}
        </div>
      </div>
    );
  }

  if (method === "consent") {
    const b = (ballot ?? {}) as { response?: string; rationale?: string };
    const current = b.response ?? "agree";
    return (
      <div className="space-y-3">
        <div>
          <span className={fieldLabel}>Do you consent?</span>
          <div className="mt-1 flex flex-wrap gap-3">
            {(["agree", "abstain", "object"] as const).map((r) => (
              <button
                key={r}
                type="button"
                onClick={() => onChange((prev) => ({ method, response: r, rationale: (prev as { rationale?: string })?.rationale ?? "" }))}
                className={`${chip} ${current === r ? chipOn : chipOff}`}
              >
                {r === "object" ? "OBJECT" : r.toUpperCase()}
              </button>
            ))}
          </div>
        </div>
        {current === "object" && (
          <div>
            <label className={fieldLabel} htmlFor="objection-rationale">
              What is the objection? The group has to be able to resolve it.
            </label>
            <textarea
              id="objection-rationale"
              rows={3}
              value={b.rationale ?? ""}
              onChange={(e) => onChange(() => ({ method, response: "object", rationale: e.target.value }))}
              className="mt-1 w-full px-3 py-2 rounded-control border border-default text-sm bg-surface-base"
            />
          </div>
        )}
      </div>
    );
  }

  if (method === "approval") {
    const approved: string[] = ((ballot as { approved?: string[] })?.approved ?? []) as string[];
    const toggle = (key: string) => onChange((prev) => toggleApproval(prev, key));
    return (
      <div>
        <span className={fieldLabel}>Approve every option you find acceptable</span>
        <div className="mt-1 space-y-2">
          {options.map((o) => (
            <label
              key={o.key}
              className="flex items-center gap-3 px-3 py-2 rounded-control border border-default bg-surface-base cursor-pointer"
            >
              <input
                type="checkbox"
                checked={approved.includes(o.key)}
                onChange={() => toggle(o.key)}
                className="h-4 w-4"
              />
              <span className="text-sm text-fg-primary">{o.label}</span>
            </label>
          ))}
        </div>
      </div>
    );
  }

  if (method === "dot") {
    const allocations: Record<string, number> =
      ((ballot as { allocations?: Record<string, number> })?.allocations ?? {}) as Record<string, number>;
    const spent = Object.values(allocations).reduce((s, n) => s + (n || 0), 0);
    const remaining = dotBudget - spent;
    const nudge = (key: string, by: number) =>
      onChange((prev) => nudgeDot(prev, key, by, dotBudget));
    return (
      <div>
        <span className={fieldLabel}>
          Spend your {dotBudget} dots — {remaining} left
        </span>
        <div className="mt-1 space-y-2">
          {options.map((o) => {
            const value = allocations[o.key] ?? 0;
            return (
              <div
                key={o.key}
                className="flex items-center justify-between gap-3 px-3 py-2 rounded-control border border-default bg-surface-base"
              >
                <span className="text-sm text-fg-primary">{o.label}</span>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    aria-label={`one fewer dot for ${o.label}`}
                    onClick={() => nudge(o.key, -1)}
                    disabled={value <= 0}
                    className="w-11 h-11 rounded-control border border-default disabled:opacity-40"
                  >
                    −
                  </button>
                  <span className="w-6 text-center font-mono text-sm text-fg-primary">{value}</span>
                  <button
                    type="button"
                    aria-label={`one more dot for ${o.label}`}
                    onClick={() => nudge(o.key, 1)}
                    disabled={remaining <= 0}
                    className="w-11 h-11 rounded-control border border-default disabled:opacity-40"
                  >
                    +
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (method === "score") {
    const scores: Record<string, number> =
      ((ballot as { scores?: Record<string, number> })?.scores ?? {}) as Record<string, number>;
    return (
      <div>
        <span className={fieldLabel}>Rate each option from 0 to 5</span>
        <div className="mt-1 space-y-2">
          {options.map((o) => (
            <div
              key={o.key}
              className="flex items-center justify-between gap-3 px-3 py-2 rounded-control border border-default bg-surface-base"
            >
              <span className="text-sm text-fg-primary">{o.label}</span>
              <div className="flex gap-1">
                {[0, 1, 2, 3, 4, 5].map((n) => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => onChange((prev) => setScore(prev, o.key, n))}
                    className={`w-11 h-11 rounded-control border border-default text-sm ${
                      scores[o.key] === n ? chipOn : chipOff
                    }`}
                  >
                    {n}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // ranked
  const ranking: string[] = ((ballot as { ranking?: string[] })?.ranking ?? []) as string[];
  const unranked = options.filter((o) => !ranking.includes(o.key));
  const move = (i: number, by: number) => onChange((prev) => moveInRanking(prev, i, by));
  const label = (key: string) => options.find((o) => o.key === key)?.label ?? key;

  return (
    <div className="space-y-3">
      <div>
        <span className={fieldLabel}>Your order of preference</span>
        {ranking.length === 0 ? (
          <p className="mt-1 text-sm text-fg-secondary">
            Nothing ranked yet — add options from below, best first.
          </p>
        ) : (
          <ol className="mt-1 space-y-2">
            {ranking.map((key, i) => (
              <li
                key={key}
                className="flex items-center justify-between gap-3 px-3 py-2 rounded-control border border-default bg-surface-base"
              >
                <span className="text-sm text-fg-primary">
                  {i + 1}. {label(key)}
                </span>
                <div className="flex gap-2">
                  <button
                    type="button"
                    aria-label={`move ${label(key)} up`}
                    onClick={() => move(i, -1)}
                    disabled={i === 0}
                    className="w-11 h-11 rounded-control border border-default disabled:opacity-40"
                  >
                    ↑
                  </button>
                  <button
                    type="button"
                    aria-label={`move ${label(key)} down`}
                    onClick={() => move(i, 1)}
                    disabled={i === ranking.length - 1}
                    className="w-11 h-11 rounded-control border border-default disabled:opacity-40"
                  >
                    ↓
                  </button>
                  <button
                    type="button"
                    aria-label={`remove ${label(key)} from the ranking`}
                    onClick={() => onChange((prev) => removeFromRanking(prev, key))}
                    className="w-11 h-11 rounded-control border border-default"
                  >
                    ×
                  </button>
                </div>
              </li>
            ))}
          </ol>
        )}
      </div>
      {unranked.length > 0 && (
        <div>
          <span className={fieldLabel}>Not ranked — ties for last</span>
          <div className="mt-1 flex flex-wrap gap-2">
            {unranked.map((o) => (
              <button
                key={o.key}
                type="button"
                onClick={() => onChange((prev) => addToRanking(prev, o.key))}
                className={`${chip} ${chipOff}`}
              >
                + {o.label}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
